import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import { Providers } from './providers';
import { Toaster } from '@/components/ui/sonner';
import Header from '@/components/common/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 🧩 Required for DocuSeal embed to work */}
        <Script src="https://docuseal.co/embed.js" strategy="beforeInteractive" />
      </head>
      <body className="font-marcellus antialiased" suppressHydrationWarning={true}>
        <Providers>
          <div className="h-screen flex flex-col">
            <Header>
              <main className="flex-1">{children}</main>
            </Header>
          </div>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
