services:
  db:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: indianweddings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  redis:
    image: redis:alpine
    container_name: redis-teo
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
 
volumes:
  postgres_data:
  redis-data: