export const API_URLS = {
  auth: {
    validateUser: '/auth/validate/user',
    adminLogin: '/auth/admin/login',
    createAdmin: '/auth/admin/create',
    verifyOtp: '/auth/admin/verify-otp',
    resetPassword: '/auth/admin/reset-password',
    currentAdmin: '/auth/admin/me',
    adminLogout: '/auth/admin/logout',
    adminForgotPassword: '/auth/admin/send-reset-email',
    lastTimeOptSent: '/auth/admin/last-time-otp-sent',
  },
  vendorAuth: {
    signup: '/auth/vendor/signup',
    vendorLogin: '/auth/vendor/login',
    verifyOtp: '/auth/vendor/verify-otp',
    resetPassword: '/auth/vendor/reset-password',
    currentVendor: '/auth/vendor/me',
    vendorLogout: '/auth/vendor/logout',
    vendorForgotPassword: '/auth/vendor/send-reset-email',
    lastTimeOptSent: '/auth/vendor/last-time-otp-sent',
  },
  userAuth: {
    userSignup: '/auth/user/signup',
    userLogin: '/auth/user/login',
    currentUser: '/auth/user/me',
    userLogout: '/auth/user/logout',
  },
  teamMemberAuth: {
    teamMemberLogin: '/auth/team-member/login',
    currentTeamMember: '/auth/team-member/me',
    teamMemberLogout: '/auth/team-member/logout',
    teamMemberForgotPassword: '/auth/team-member/send-reset-email',
    teamMemberVerifyOtp: '/auth/team-member/verify-otp',
    teamMemberLastTimeOptSent: '/auth/team-member/last-time-otp-sent',
    teamMemberResetPassword: '/auth/team-member/reset-password',
  },
  admin: {
    deleteById: (id: string) => `/admin/team/${id}`,
    getTeams: '/admin/get/teams',
    createTeams: '/admin/teams',
    getSingleTeam: (teamId: string) => `/admin/get/team/${teamId}`,
    updateTeamWithMembers: (teamId: string) => `/admin/team/${teamId}/members`,

    create: '/admin/create',
    getVendors: '/admin/list',
    getSingleVendor: (id: string) => `/admin/${id}`,
    updateVendorById: (id: string) => `/admin/update/${id}`,
    updateVendorStatus: (id: string) => `/admin/update-status/vendor-id/${id}`,
    bulkUpdateVendorStatus: '/admin/bulk-update-status',
    exportVendorsWithIdsCsv: '/admin/export-vendor-with-ids/csv',
    event: '/admin/events',
  },
  lead: {
    create: '/lead/create',
    getLeads: '/lead/get-all',
    getSingleLeads: (id: string) => `/lead/get-by-id/${id}`,
    getBoardLeads: '/lead/get-board-data',
    getVendorsByLead: (id: string) => `/lead/get-vendors-by-lead-id/${id}`,
    updateLeadById: (id: string) => `/lead/update/lead-id/${id}`,
    updateLeadStatus: (id: string) => `/lead/update-status/lead-id/${id}`,
    updateLeadSaveStatus: (id: string) => `/lead/save-status/lead-id/${id}`,
    bulkUpdateLeadStatus: '/lead/bulk-update-status',
    exportLeadsWithIdsCsv: '/lead/export-lead-with-ids/csv',
    getAllVendorsForLead: (id: string) => `/lead/get-all-vendors-for-lead/${id}`,

    assignVendorsToLead: '/leads/assign-vendors',
  },
  vendor: {
    create: '/vendor/create',
    getVendors: '/vendor/list',
    getSingleVendor: (id: string) => `/vendor/${id}`,
    updateVendorById: (id: string) => `/vendor/update/${id}`,
    updateVendorStatus: (id: string) => `/vendor/update-status/vendor-id/${id}`,
    bulkUpdateVendorStatus: '/vendor/bulk-update-status',
    exportVendorsWithIdsCsv: '/vendor/export-vendor-with-ids/csv',
    event: '/vendor/events',
    createTeams: '/vendor/teams',
    getTeams: '/vendor/get/teams',
    getSingleTeam: (teamId: string) => `/vendor/get/team/${teamId}`,
    deleteById: (id: string) => `/vendor/team/${id}`,
    updateTeamWithMembers: (teamId: string) => `/vendor/team/${teamId}/members`,
    getHomePageVendors: '/vendor/home',
  },
  vendorService: {
    create: '/vendor/service/create',
    getAllByVendor: '/vendor/get/services',
    getById: (id: string) => `/vendor/service/${id}`,
    updateById: (id: string) => `/vendor/service/update/${id}`,
    deleteById: (id: string) => `/vendor/service/${id}`,
  },
  pipeline: {
    getLeads: '/pipeline/leads',
    updateLeadStatus: (id: string) => `/pipeline/leads/${id}/status`,
    updateLead: (id: string) => `/pipeline/leads/${id}`,
    archiveLead: (id: string) => `/pipeline/leads/${id}/archive`,
  },
  proposal: {
    base: '/proposals',
    getAll: '/proposals',
    create: '/proposals/create',
    getById: (id: string) => `/proposals/${id}`,
    getByLead: (leadId: string) => `/proposals/lead/${leadId}`,
    update: (id: string) => `/proposals/${id}`,
    delete: (id: string) => `/proposals/${id}`,
    send: (id: string) => `/proposals/${id}/send`,
    saveDraft: (leadId: string) => `/proposals/draft/${leadId}`,
    getDraft: (leadId: string) => `/proposals/draft/${leadId}`,
    saveVersion: (proposalId: string) => `/proposals/version/${proposalId}`,
    finalize: (proposalId: string) => `/proposals/finalize/${proposalId}`,
    assignVendors: (proposalId: string) => `/proposals/assign-vendors/${proposalId}`,
    getUserProposals: (clientId: string) => `/proposals/user/${clientId}`,
    updateStatus: (proposalId: string) => `/proposals/${proposalId}/status`,
    sendEmail: (proposalId: string) => `/proposals/${proposalId}/send-email`,
  },
  proposalTemplate: {
    getAll: '/proposal-templates/templates',
    getById: (id: string) => `/proposal-templates/templates/${id}`,
    create: '/proposal-templates/templates',
    update: (id: string) => `/proposal-templates/templates/${id}`,
    delete: (id: string) => `/proposal-templates/templates/${id}`,
    seed: '/proposal-templates/templates/seed',
  },
  landingPage: {
    updateSection1: '/home/section/section1',
    updateSection2: '/home/section/section2',
    updateSection3: '/home/section/section3',
    updateSection4: '/home/section/section4',
    updateSection5: '/home/section/section5',
    updateSection6: '/home/section/section6',
  },
  weddingPlan: {
    create: '/wedding-plan/create',
    updateServiceStatus: (serviceId: string) => `/wedding-plan/service/${serviceId}/status`,
  },
  notifications: {
    getAll: '/notifications',
    markAsRead: (id: string) => `/notifications/${id}/read`,
    markAllAsRead: '/notifications/mark-all-read',
  },
};

export const API_QUERY_KEYS = {
  auth: {
    validateUser: 'validateUser',
    adminLogin: 'adminLogin',
    createAdmin: 'createAdmin',
    sendResetEmail: 'sendResetEmail',
    verifyOtp: 'verifyOtp',
    resetPassword: 'resetPassword',
    currentAdmin: 'currentAdmin',
    adminForgotPassword: 'adminForgotPassword',

    currentlyTeamMember: 'currentlyTeamMember',
  },
  admin: {
    getTeams: 'getAdminTeams',
    getSingleTeam: 'getSingleAdminTeam',

    createVendor: 'createVendorAdmin',
    getVendors: 'getVendorsAdmin',
    getSingleVendor: 'getSingleVendorAdmin',
    updateVendorById: 'updateVendorByIdAdmin',
    updateVendorStatus: 'updateVendorStatusAdmin',
    bulkUpdateVendorStatus: 'bulkUpdateVendorStatusAdmin',
    exportVendorsWithIdsCsv: 'exportVendorsWithIdsCsvAdmin',
    validateUser: 'validateUserAdmin',
    vendorLogin: 'vendorLoginAdmin',
    sendResetEmail: 'sendResetEmailAdmin',
    verifyOtp: 'verifyOtpAdmin',
    resetPassword: 'resetPasswordAdmin',
    currentVendor: 'currentVendorAdmin',
    vendorForgotPassword: 'vendorForgotPasswordAdmin',
    deleteById: 'deleteAdminTeamById',
    updateTeamWithMembers: 'updateTeamWithMembersAdmin',
  },
  lead: {
    createLead: 'createLead',
    getLeads: 'getLeads',
    getSingleLead: 'getSingleLead',
    getBoardLeads: 'getBoardLeads',
    getVendorsByLeadId: 'getVendorsByLeadId',
    updateLeadById: 'updateLeadById',
    updateLeadStatus: 'updateLeadStatus',
    bulkUpdateLeadStatus: 'bulkUpdateLeadStatus',
    getAllVendorsForLead: 'getAllVendorsForLead',
    assignVendorsToLead: 'assignVendorsToLead',
  },
  event: {
    getAllEvents: 'getAllEvents',
  },
  vendor: {
    createVendor: 'createVendor',
    getVendors: 'getVendors',
    getSingleVendor: 'getSingleVendor',
    updateVendorById: 'updateVendorById',
    updateVendorStatus: 'updateVendorStatus',
    bulkUpdateVendorStatus: 'bulkUpdateVendorStatus',
    exportVendorsWithIdsCsv: 'exportVendorsWithIdsCsv',
    validateUser: 'validateUser',
    vendorLogin: 'vendorLogin',
    sendResetEmail: 'sendResetEmail',
    verifyOtp: 'verifyOtp',
    resetPassword: 'resetPassword',
    currentVendor: 'currentVendor',
    vendorForgotPassword: 'vendorForgotPassword',
    getTeams: 'getTeams',
    getSingleTeam: 'getSingleTeam',
    deleteById: 'deleteVendorTeamById',
    updateTeamWithMembers: 'updateTeamWithMembers',
    getVendorsHomePage: 'getVendorsHomePage',
  },
  vendorService: {
    createVendorService: 'createVendorService',
    getAllByVendor: 'getAllVendorServices',
    getById: 'getVendorServiceById',
    updateById: 'updateVendorServiceById',
    deleteById: 'deleteVendorServiceById',
  },
  user: {
    userSignup: 'userSignup',
    userLogin: 'userLogin',
    currentUser: 'currentUser',
    userLogout: 'userLogout',
  },
  pipeline: {
    getLeads: 'pipelineLeads',
    updateLeadStatus: 'updatePipelineLeadStatus',
  },
  proposal: {
    getAll: 'getAllProposals',
    create: 'createProposal',
    getById: 'getProposalById',
    getByLead: 'getProposalsByLead',
    update: 'updateProposal',
    delete: 'deleteProposal',
    send: 'sendProposal',
    saveDraft: 'saveProposalDraft',
    getDraft: 'getProposalDraft',
    saveVersion: 'saveProposalVersion',
    finalize: 'finalizeProposal',
    assignVendors: 'assignVendors',
    getUserProposals: 'getUserProposals',
    updateStatus: 'updateStatus',
    sendEmail: 'sendEmail',
  },

  proposalTemplate: {
    getAll: 'getAllTemplates',
    getById: 'getTemplateById',
    create: 'createTemplate',
    update: 'updateTemplate',
    delete: 'deleteTemplate',
    seed: 'seedTemplates',
  },
  weddingPlan: {
    create: 'createWeddingPlan',
    updateServiceStatus: 'updateServiceStatus',
  },
  notifications: {
    getAll: 'getAll',
    markAsRead: 'markAsRead',
    markAllAsRead: 'markAllAsRead',
  },
};
