export const VARIABLES = [
  '{{client.name}}',
  '{{company.contactName}}',
  '{{company.name}}',
  '{{dateISO}}',
  '{{wedding.theme}}',
  '{{wedding.destination}}',
  '{{wedding.venue}}',
  '{{wedding.guestCount}}',
  '{{wedding.specialRequirements}}',
  '{{#each goals}}{{this}}{{/each}}',
  '{{wedding.date}}',
  '{{wedding.venueFeatures}}',
  '{{#each events}}{{name}}, {{date}}, {{startTime}}, {{endTime}}, {{location}}{{/each}}',
  '{{#each services}}{{name}}, {{vendor.name}}, {{price}}, {{notes}}{{/each}}',
  '{{wedding.colorPalette}}',
  '{{designElements}}',
  '{{decorElements}}',
  '{{#each budget.items}}{{label}}, {{amount}}{{/each}}',
  '{{budget.subTotal}}',
  '{{budget.taxPercent}}',
  '{{budget.taxAmount}}',
  '{{budget.total}}',
  '{{budget.deposit}}',
  '{{budget.interim}}',
  '{{budget.interimDueDate}}',
  '{{budget.final}}',
  '{{budget.finalDueDate}}',
];
